apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-serviceaccount.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - external-secret-db.yaml
  - ingress.yaml
