apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: desafio/api
    newName: 000000000000.dkr.ecr.eu-south-2.amazonaws.com/desafio/api
    newTag: latest
  - name: desafio/frontend
    newName: 000000000000.dkr.ecr.eu-south-2.amazonaws.com/desafio/frontend
    newTag: latest
